### ISSUE TITLE
Page not found when using Traefik

### ISSUE THREAD

**Issue by xplosionmind** [Mailtrain-org/mailtrain#1023]
Hello, the following is my `docker-compose.yml`. I pasted in here the content of `docker-compose.override.yml`   
Once I visit `https://mailtrain.tommi.space`, I get `404 page not found` (see screenshot at the bottom). Where is my error (note: Traefik is up and running correctly, I have other containers which use it and they are ok)

```
version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mailtrain
      - MYSQL_DATABASE=mailtrain
      - MYSQL_USER=mailtrain
      - MYSQL_PASSWORD=mailtrain
    volumes:
      - mailtrain-mysq-data:/var/lib/mysql
    restart: always
  redis:
    image: redis:3.0
    volumes:
      - mailtrain-redis-data:/data
    restart: always
  mailtrain:
    build: ./
    image: mailtrain:latest
    container_name: mailtrain
    hostname: mailtrain
    depends_on:
      - mysql
      - redis
    volumes:
      - mailtrain-node-config:/app/config
      - mailtrain-node-data:/app/public/grapejs/uploads
      - mailtrain-node-data:/app/public/mosaico/uploads
      - mailtrain-node-reports:/app/protected/reports
    ports:
      - "3000:3000"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.mailtrain-trusted.backend=mailtrain-trusted"
      - "traefik.mailtrain-trusted.frontend.rule=Host:mailtrain.tommi.space"
      - "traefik.mailtrain-trusted.frontend.headers.SSLRedirect=true"
      - "traefik.mailtrain-trusted.port=3000"
      - "traefik.mailtrain-trusted.protocol=http"
volumes:
  mailtrain-mysq-data: {}
  mailtrain-redis-data: {}
  mailtrain-node-data: {}
  mailtrain-node-config: {}
  mailtrain-node-reports: {}
```

The error message:
![Screenshot 2021-03-14 at 5 47 19 PM](https://user-images.githubusercontent.com/42862428/111076685-9eb96d80-84ed-11eb-9ef3-de8b44d4281b.jpg)

Thank y'all very much in advance!
