### ISSUE TITLE
Info: Waiting for MySQL Server

### ISSUE THREAD

**Issue by martijnmichel** [Mailtrain-org/mailtrain#1094]
docker-compose up keeps hanging on this while trying to connect to a localhost mysql db instead of the containerized one.

I've tried nearly a thousand different combinations all resulting in this message.
I've also changed the docker-entrypoint.sh removing the if expression to wait for the db, but it still gives this message.

Is it even possible to use mailtrain with another db instance than the docker-composed one?

```
version: '3'
  
services:

  redis:
    image: redis:5
    restart: always
    volumes:
      - redis-data:/data

  mailtrain:

    image: mailtrain/mailtrain:latest
    restart: always
    ports:
      - "3000:3000"
      - "3003:3003"
      - "3004:3004"

    volumes:
      - mailtrain-files:/app/server/files
    environment:

      MYSQL_PASSWORD: "randomtrain"
      MYSQL_USER: "mailtrain_randadmin"
      MYSQL_HOST: "localhost" // tried nearly every combo i could think of here and with other settings

      URL_BASE_TRUSTED: "https://marketing.sog.asd"
      URL_BASE_SANDBOX: "https://sbox-mailtrain.sdfid.fgpp"
      URL_BASE_PUBLIC: "https://lists.sdfg.fdg"

      ADMIN_ACCESS_TOKEN: "604e02fdgdhjFAKEFAKEFAKEkgt978eyt444degfjhgfks99175d8"

volumes:
  redis-data:
  mongo-data:
  mailtrain-files:
```
