### ISSUE TITLE
Sending bottleneck via AWS SES

### ISSUE THREAD

**Issue by misterioss** [Mailtrain-org/mailtrain#1106]
Hi, 
we have a problem: **average sending rate is about 68-90** emails per second.
I want to make it up to 200 emails, API allows it.

We tried:
* bigger machines for the database and Mailtrain instance (not in Docker), allocate more CPU and RAM, but Mailtrain uses ~ 20% of resources and ~ 50% when the campaign starts
* disable logs and other daemons
* delete everything from campaign_messages

We have the next setup:

Subscribers count: ~3 300 000

AWS SES via API, sending limit 200 emails/second, 10 000 000 per 24 hours

**Mailtrain**: The latest version from default branch installed on Ubuntu 18.04, 
> c5.2xlarge 8 vCPU, 16 Gb RAM

![screen_shot_2021-06-23_at_14 54 46](https://user-images.githubusercontent.com/3921977/123092299-04918b80-d433-11eb-9c86-d703617e673b.png)

**Database**: MariaDB 10.5.8 on db.t3.xlarge
> 2 cores, 4vCPU, 16 GiB

![screen_shot_2021-06-23_at_16 57 11](https://user-images.githubusercontent.com/3921977/123109698-1fb8c700-d444-11eb-8387-5a97e0094a2d.png)

CPU usage by database: 
![screen_shot_2021-06-23_at_15 21 14](https://user-images.githubusercontent.com/3921977/123095584-e168db00-d436-11eb-8730-8ae53586904b.png)

Write IOPS by database, (Max 3000 IOPS)

![screen_shot_2021-06-23_at_17 00 27](https://user-images.githubusercontent.com/3921977/123110305-a077c300-d444-11eb-9e93-369bf5fccc49.png)

production.yaml config:
```
user: *******
group: *******
roUser: nobody
roGroup: nobody

www:
  host: "127.0.0.1"
  proxy: true
  secret: "*******"
  trustedUrlBase: https://*******.com
  sandboxUrlBase: https://sbox.*******.com
  publicUrlBase: https://list.*******.com


mysql:
  password: "**********************"
  user: "*******"
  host: "*************.rds.amazonaws.com"

redis:
  enabled: true

log:
  level: info

builtinZoneMTA:
  enabled: false
  log:
    level: warn

queue:
  processes: 16

cors:
  # Allow subscription widgets to be embedded
  origins: ['http://*******.***/', 'http://www.*******.****/']
```
AWS SES sending settings:
![screen_shot_2021-06-23_at_16 59 01](https://user-images.githubusercontent.com/3921977/123110047-6a3a4380-d444-11eb-9a2e-26fcb2b250c2.png)

@bures do you have any ideas? What else we should try?

Thank you.
