### ISSUE TITLE
Blank screen on install

### ISSUE THREAD

**Issue by ghost** [Mailtrain-org/mailtrain#1111]
I tried installing Mailtrain via Docker for local installation and all I'm getting is a blank screen when trying to reach the UI.

In mailtrain_mysql_1 I found this, not sure if this is an issue
```
2021-06-28 22:05:31 8 [Warning] Aborted connection 8 to db: 'unconnected' user: 'unauthenticated' host: '192.168.0.3' (This connection closed normally without authentication)
2021-06-28 22:05:31 0 [Note] InnoDB: Buffer pool(s) load completed at 210628 22:05:31
2021-06-28 22:05:32 10 [Warning] Aborted connection 10 to db: 'mailtrain' user: 'mailtrain' host: '192.168.0.3' (Got an error reading communication packets)
```

**Comment by PhilippeAccorsi** [comment]
Hi,

Do you sure mysql is listening on docker ip network ? By default, docker network use ip range like that `172.xx.xx.xx`. So, if your mysql server is not running on same docker network (maybe mysql is installed on your host) you need to adjust mysql configuration.

**Comment by jmhmd** [comment]
I also had this issue - the problem for me was that I hadn't set the `docker-compose` environment variables for `URL_BASE_TRUSTED`, `URL_BASE_SANDBOX`, and `URL_BASE_PUBLIC`. The page was trying to request assets from `localhost`, which doesn't work if not on a local machine.

Open your `docker-compose.yml` file, and add the environment variables like so:
```yaml
mailtrain:
    image: mailtrain/mailtrain:latest
    environment:
    - URL_BASE_TRUSTED=https://mailtrain.example.com
    - URL_BASE_SANDBOX=https://sbox-mailtrain.example.com
    - URL_BASE_PUBLIC=https://lists.example.com
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - mailtrain-files:/app/server/files
```

It would be helpful to add this as a step to the docs.

**Comment by RobinDev03** [comment]
Hi, 

same issue here.
During Boot-Process it says something like "Mailtrain is starting. Try again later" and in console, I get 500-Errors. When it is started, I only get a Whitescreen, bot 200 in console...
```log
mailtrain_1  | info HTTP GET /lists 500 40.661 ms - -
mailtrain_1  | info HTTP GET /client/mailtrain.css 500 2.753 ms - -
mailtrain_1  | info HTTP GET /static-npm/jquery.min.js 500 2.809 ms - -
mailtrain_1  | info HTTP GET /static-npm/popper.min.js 500 1.697 ms - -
mailtrain_1  | info HTTP GET /static-npm/bootstrap.min.js 500 1.740 ms - -
mailtrain_1  | info HTTP GET /static-npm/coreui.min.js 500 1.430 ms - -
mailtrain_1  | info HTTP GET /static/favicon.ico 500 2.275 ms - -
mailtrain_1  | info HTTP GET / 500 2.517 ms - -
mailtrain_1  | info Senders Worker process 1 started
mailtrain_1  | info Senders Worker process 2 started
mailtrain_1  | info Senders Worker process 3 started
mailtrain_1  | info Senders Worker process 0 started
mailtrain_1  | info Senders Worker process 4 started
mailtrain_1  | info Senders Master sender process started
mailtrain_1  | info Triggers Starting trigger check service
mailtrain_1  | info GDPR Starting GDPR cleanup service
mailtrain_1  | info ReportProcessor Trying to start worker because runningWorkersCount=0 maxWorkersCount=1
mailtrain_1  | info ReportProcessor No more reports to start a worker for
mailtrain_1  | info Service All services started
mailtrain_1  | info HTTP GET / 200 8.804 ms - -
mailtrain_1  | info HTTP GET /client/root.js 200 6.294 ms - -
mailtrain_1  | info HTTP GET / 200 2.160 ms - -
```


I also have the database "issue": 
```
mailtrain_1  | info sql Database check completed
mysql_1      | 2022-11-28 14:49:01 10 [Warning] Aborted connection 10 to db: 'mailtrain' user: 'mailtrain' host: '172.18.0.5' (Got an error reading communication packets)
```


> Hi,
> 
> Do you sure mysql is listening on docker ip network ? By default, docker network use ip range like that `172.xx.xx.xx`. So, if your mysql server is not running on same docker network (maybe mysql is installed on your host) you need to adjust mysql configuration.

@PhilippeAccorsi it doesn't help for me.

**Comment by phboett** [comment]
Having the same issue and am at the same state as you @RobinDev03 . Did you solve this problem somehow?

**Comment by RobinDev03** [comment]
It seems so, but dont ask how.... After 3 weeks, it worked... but i changed nothing.... cant help here, sorry

**Comment by phboett** [comment]
Hmm weird. Did you let it run in the background and it just started working or did it randomly work after a few restarts? Can you tell me about your setup? 
I use a reverse proxy using the jwilder/nginx-proxy image and my docker-compose.yml for mailtrain looks like this


    version: '3'
    services:
      mysql:
        image: mariadb:10.4
        networks:
        - "common_mail"
        environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        volumes:
        - mysql-data:/var/lib/mysql
    
      redis:
        networks:
        - "common_mail"
        image: redis:5
        volumes:
        - redis-data:/data
    
      mongo:
        image: mongo:4-xenial
        networks:
        - "common_mail"
        volumes:
        - mongo-data:/data/db
    
      mailtrain:
        networks: ["common_mail", "net"]
        image: mailtrain/mailtrain:latest
        container_name: "mailtrain"
        depends_on:
        - redis
        - mysql
        - mongo
    
        volumes:
        - mailtrain-files:/app/server/files
    
        environment:
        - URL_BASE_TRUSTED="https://fake.com"
        - URL_BASE_SANDBOX="https://fake.com/sbox"
        - URL_BASE_PUBLIC="https://fake.com/lists"
    
    
      nginx_gateway:
        image: nginx:latest
        networks: ["common_mail", "net"]
        container_name: "nginx_gateway"
        restart: "always"
        depends_on:
        - "mailtrain"
        environment:
        - VIRTUAL_HOST=fake.com
        - LETSENCRYPT_HOST=fake.com
    
    
    volumes:
      mysql-data:
      redis-data:
      mongo-data:
      mailtrain-files:
    
    networks:
      net:
        external: true
      common_mail:
        internal: true

**Comment by RobinDev03** [comment]
It just ran in the background. I'm not sure, if I restarted the host, but I don't think so.
I have a docker-host running deb11 with Docker version 20.10.5+dfsg1, build 55c4c88

```
version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
    - redis-data:/data

  mongo:
    image: mongo:4-xenial
    volumes:
    - mongo-data:/data/db

  mailtrain:
    image: mailtrain/mailtrain:latest
    environment:
    - URL_BASE_TRUSTED=https://mailtrain.some.domain
    - URL_BASE_SANDBOX=https://mailtrainsbox.some.domain
    - URL_BASE_PUBLIC=https://lists.some.domain
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - mailtrain-files:/app/server/files

volumes:
  mysql-data:
  redis-data:
  mongo-data:
  mailtrain-files:
```
