### ISSUE TITLE
TIMEZONE not showing local time

### ISSUE THREAD

**Issue by jonathanmmm** [Mailtrain-org/mailtrain#1221]
I am using 
```
- /etc/localtime:/etc/localtime:ro
- /etc/timezone:/etc/timezone:ro
```
in `docker-compose.yml`
executing the `date` command in the container gives the correct time.

But after I did today an import of subscribers it shows in the list in the column `created` `in 2 hours` (meaning the future), as I live in UTC+2, it seems to just use UTC, not recalculating either only in the frontend UTC not to the correct local time of the server or also in the backend. The second could be problamatic when using schedules. But maybe schedules are set to respect the local set TIMEZONE of each subscriber, e.g. that everyone gets a newsletter in the morning at 8 a.m. in their local time.

**Comment by l4b4r4b4b4** [comment]
I noticed the same thing a while ago and can confirm, all the steps!
![grafik](https://user-images.githubusercontent.com/13406997/168655189-0dc291be-ec8d-4f42-afa3-092659bb8787.png)

@jonathanmmm Did you find a solution for the bug? Maybe setting System time equal to UTC?
My guess is also, that this bug prevents triggered campaigns from being fired. @bures Could that be the issue for it? 

**Update 1**
Commenting out the time related volumes for all containers fixes the creation time problem! Lets see if automation works now...
```
...
volumes:
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
...
```
![grafik](https://user-images.githubusercontent.com/13406997/168658463-225df6dd-17cb-4176-bcc2-f4e005e2b94e.png)

**Heureka**
It does work now :)

**Comment by jonathanmmm** [comment]
My guess when commenting them out, is that the container now internally also uses UTC (could you check that with `date` command inside the container)?
And that way no shift happens (at least in the web ui, with creation).

**Comment by l4b4r4b4b4** [comment]
well this was what I was hoping for and it indeed does have that effect. It is important to do it on all containers though!
```
bash-5.0# date
Mon May 16 18:56:00 UTC 2022
```
And by **Heureka** I ment, that the result is that automation triggers now work a intended! :smile:

**Comment by jonathanmmm** [comment]
> well this was what I was hoping for and it indeed does have that effect. It is important to do it on all containers though!
> ```
> bash-5.0# date
> Mon May 16 18:56:00 UTC 2022
> ```
> And by **Heureka** I ment, that the result is that automation triggers now work a intended! :smile: 

Great, does schedules work with the time of the recipient or with UTC?

What do you mean with all containers?

Do you mean database?

**Comment by l4b4r4b4b4** [comment]
UTC, if I understand your question correctly.
I mean I commented out the time related volumes on all containers of the mailtrain stack. Like so...
```
version: '3'
networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge
  inbound:
    external: true

services:
  mailtrain:
#    image: mailtrain/mailtrain:latest
    build: .
    depends_on:
      - mysql
      - redis
      - mongo
    links:
      - mysql
      - redis
      - mongo
    environment:
#      - PORT_TRUSTED=80
      # - WITH_LDAP=true
      # - LDAP_HOST=ldap://ldap.${DOMAIN}
      # - LDAP_BIND_USER=dn=admin,dc=domain,dc=tld
      # - LDAP_BIND_PASS=${LDAP_PASS}
      # - LDAP_UIDTAG=cn
      # - LDAP_BASEDN=ou=people,dc=domain,dc=tld
      # - LDAP_FILTER=(objectclass=AsteriskSIPUser)
      - WWW_PROXY=true
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DEFAULT_LANGUAGE=${LOCALE}
      - URL_BASE_TRUSTED=https://mailtrain.${DOMAIN}
      - URL_BASE_SANDBOX=https://sbox.${DOMAIN}
      - URL_BASE_PUBLIC=https://lists.${DOMAIN}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # ports:
    #   - "3000:3000"
    #   - "3003:3003"
    #   - "3004:3004"
    volumes:
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - mailtrain-files:/app/server/files
    networks:
      - internal
      - web
      - inbound
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailtrain.rule=Host(`mailtrain.${DOMAIN}`)"
      - "traefik.http.routers.mailtrain.entrypoints=websecure"
      - "traefik.http.routers.mailtrain.service=mailtrain"
      - "traefik.http.routers.mailtrain.tls.certresolver=myresolver"
      - "traefik.http.services.mailtrain.loadbalancer.server.port=3000"
      - "traefik.http.routers.sbox.rule=Host(`sbox.${DOMAIN}`)"
      - "traefik.http.routers.sbox.entrypoints=websecure"
      - "traefik.http.routers.sbox.service=sbox"
      - "traefik.http.routers.sbox.tls.certresolver=myresolver"
      - "traefik.http.services.sbox.loadbalancer.server.port=3003"
      - "traefik.http.routers.lists.rule=Host(`lists.${DOMAIN}`)"
      - "traefik.http.routers.lists.entrypoints=websecure"
      - "traefik.http.routers.lists.service=lists"
      - "traefik.http.routers.lists.tls.certresolver=myresolver"
      - "traefik.http.services.lists.loadbalancer.server.port=3004"
      - "com.centurylinklabs.watchtower.enable=true"

  mysql:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  mongo:
    image: mongo:4-xenial
    volumes:
      - mongo-data:/data/db
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  redis:
    image: redis:5
    volumes:
      - redis-data:/data
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


volumes:
  mysql-data:
  redis-data:
  mongo-data:
  mailtrain-files:

```
