### ISSUE TITLE
error 500 with problem downloading image from public url with proxy traefik

### ISSUE THREAD

**Issue by justin-petermann** [Mailtrain-org/mailtrain#1383]
Hello,

Your project is old in V2 but very interesting.

Every thing seems to work but we have a problem on downloading image from emails.

```
We use docker image from this part of docker-compose : 
  mailtrain:
    image: mailtrain/mailtrain:latest
    volumes:
    - /var/lib/docker/data/mailtrain/data/mailtrain-files:/app/server/files
    networks:
      mailtrain-network:
        ipv4_address: 172.21.0.100
      traefik-public:
    environment:
      WWW_PROXY: true
      URL_BASE_TRUSTED: https://mailtrain-trust.example.com
      URL_BASE_SANDBOX: https://mailtrain-sandbox.example.com
      URL_BASE_PUBLIC: https://mailtrain.example.com
```

mailtrain-1  | info HTTP GET /mosaico/img?src=https%3A%2F%2Fmailtrain.example.com%2Ffiles%2Ftemplate%2Ffile%2F1%2F50de6066d4c7121dac15e7fe0007f90e&method=resize%C2%B6ms=258,null 500 5.479 ms - 1353

When i listen on bridge on port port 3004, i see the internal connexion.
Traefik redirectect well from https://mailtrain.example.com to port 3004.

I'm not able to see log or error that could explain the file.

File 50de6066d4c7121dac15e7fe0007f90e exists : ./template/file/1/50de6066d4c7121dac15e7fe0007f90e

and i can download : https://mailtrain.example.com/files/template/file/1/50de6066d4c7121dac15e7fe0007f90e

Do you lnow an issue please ?

Hope v3 will be good, it seems to be a good project.

Best regards,
Justin
