### ISSUE TITLE
Docker container fails to deploy: cannot find module config

### ISSUE THREAD

**Issue by pqvst** [Mailtrain-org/mailtrain#288]
I tried to deploy the docker container as per the instructions, which resulted in the error "cannot find module config". The non-Docker install script worked fine. Both on Ubuntu 16.

**Comment by witzig** [comment]
Any chance you can provide the logs from building the Docker image?

@theyough, as you gave a thumbs up, did you have the same problem?

**Comment by programster** [comment]
Hello there,
I tried deploying using the deployment instructions and noticed that I got the following when I ran the docker-compose up command:

![stuart ubuntu 10 2 0 11 - byobu_370](https://user-images.githubusercontent.com/5709838/30891071-c68dbd16-a328-11e7-9f37-48862e8caead.png)

So I looked at the Dockerfile and saw this:
```
FROM node:8.1
```
I see that the [node image is now on 8.6](https://hub.docker.com/_/node/) so I just changed it to that. After performing this change, it appears to have worked for me.

![selection_372](https://user-images.githubusercontent.com/5709838/30891115-02df0d06-a329-11e7-9805-5c2b610ac272.png)

So I think we **just need to update the dockerfile to fix this issue**? Would appreciate it if others can confirm this fixes it for them.

## Extra Stuff
I've been away from the project a while and just wanted to ask why we are now defaulting to port 3000? Can we not default to port 80 and just provide instructions for others on how to change it to something else if they want to? Hopefully this is as easy as changing the override file from:

```
version: '2'
services:
  mysql:
    restart: always
  redis:
    restart: always
  mailtrain:
    build: ./
    # volumes:
      # - ./:/app
    ports:
      - "3000:3000"
    restart: always
```
to:
```
version: '2'
services:
  mysql:
    restart: always
  redis:
    restart: always
  mailtrain:
    build: ./
    # volumes:
      # - ./:/app
    ports:
      - "80:3000"
    restart: always
```

Are areas of the code that are hardcoded to be port 3000? (In which case we just need them to dynamically figure out the port) I've had this in the past with things like Gitlab but I think they resolved this.
