### ISSUE TITLE
[V2] Page for templates not visitable

### ISSUE THREAD

**Issue by Avalarion** [Mailtrain-org/mailtrain#571]
Hey together,

after reading of how cool mailtrain is I wanted to try this for one of our projects so I wrote this docker-compose.yml:

```
version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - ./data/mysql:/var/lib/mysql
    networks:
      - internal

  redis:
    image: redis:5
    volumes:
    - ./data/redis:/data
    networks:
      - internal

  mongo:
    image: mongo:4-xenial
    volumes:
    - ./data/mongo:/data/db
    networks:
      - internal

  mailtrain:
    image: mailtrain/mailtrain:latest
    command: " --trustedUrlBase https://newsletter.placeholder.de --sandboxUrlBase https://box.newsletter.placeholder.de --publicUrlBase https://public.newsletter.placeholder.de --withProxy"
    labels:
      traefik.enable: "true"
      traefik.newsletter.backend: "newsletter_placeholder_de"
      traefik.newsletter.frontend.rule: "Host:newsletter.placeholder.de"
      traefik.newsletter.frontend.port: "3000"
      traefik.newsletter.frontend.headers.STSSeconds: "31536000"
      traefik.newsletter.frontend.headers.STSIncludeSubdomains: "true"
      traefik.newsletter.frontend.headers.STSPreload: "true"
      traefik.box.backend: "box_newsletter_placeholder_de"
      traefik.box.frontend.rule: "Host:box.newsletter.placeholder.de"
      traefik.box.frontend.port: "3003"
      traefik.box.frontend.headers.STSSeconds: "31536000"
      traefik.box.frontend.headers.STSIncludeSubdomains: "true"
      traefik.box.frontend.headers.STSPreload: "true"
      traefik.sbox.backend: "public_newsletter_placeholder_de"
      traefik.public.frontend.rule: "Host:public.newsletter.placeholder.de"
      traefik.public.frontend.port: "3004"
      traefik.public.frontend.headers.STSSeconds: "31536000"
      traefik.public.frontend.headers.STSIncludeSubdomains: "true"
      traefik.public.frontend.headers.STSPreload: "true"
      traefik.docker.network: "web"
    volumes:
    - ./data/mailtrain/files:/app/server/files
    - ./data/mailtrain/reports:/app/protected/reports
    networks:
      - internal
      - web

networks:
  internal:
    external:
      name: newsletter_placeholder_de
  web:
    external:
      name: web
```

After checking the newsletter.placeholder.de  page I successfully logged in and it looks like I am able to do nearly everything but one thing: Work with Templates.

It shows the following problems in console:

```
Download the React DevTools for a better development experience: https://fb.me/react-devtools
helpers.js:264 Uncaught ReferenceError: key is not defined
    at getTemplateTypes (helpers.js:264)
    at new List (List.js:40)
    at new TargetClassWithCtors (decorator-helpers.js:60)
    at constructClassInstance (react-dom.development.js:11326)
    at updateClassComponent (react-dom.development.js:14652)
    at beginWork (react-dom.development.js:15609)
    at performUnitOfWork (react-dom.development.js:19277)
    at workLoop (react-dom.development.js:19317)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
```

```
The above error occurred in the <TargetClassWithCtors> component:
    in TargetClassWithCtors (created by ComponentMixinsInner)
    in ComponentMixinsInner (created by NamespacesConsumerComponent)
    in NamespacesConsumerComponent (created by WithMergedOptions)
    in WithMergedOptions (created by Context.Consumer)
    in WithMergedOptions(NamespacesConsumerComponent) (created by LoadNamespace)
    in LoadNamespace (created by WithMergedOptions)
    in WithMergedOptions (created by Context.Consumer)
    in LoadNamespace(ComponentMixinsInner) (created by RequiresAuthenticatedUser)
    in RequiresAuthenticatedUser (created by Context.Consumer)
    in ComponentMixinsOuter (created by TargetClassWithCtors)
    in div (created by TargetClassWithCtors)
    in main (created by TargetClassWithCtors)
    in div (created by TargetClassWithCtors)
    in div (created by TargetClassWithCtors)
    in TargetClassWithCtors (created by ComponentMixinsInner)
    in ComponentMixinsInner (created by NamespacesConsumerComponent)
    in NamespacesConsumerComponent (created by WithMergedOptions)
    in WithMergedOptions (created by Context.Consumer)
    in WithMergedOptions(NamespacesConsumerComponent) (created by LoadNamespace)
    in LoadNamespace (created by WithMergedOptions)
    in WithMergedOptions (created by Context.Consumer)
    in LoadNamespace(ComponentMixinsInner) (created by Context.Consumer)
    in ComponentMixinsOuter (created by Route)
    in Route (created by TargetClassWithCtors)
    in Switch (created by TargetClassWithCtors)
    in TargetClassWithCtors (created by ComponentMixinsInner)
    in ComponentMixinsInner (created by Context.Consumer)
    in ComponentMixinsOuter (created by Route)
    in Route (created by withRouter(ComponentMixinsOuter))
    in withRouter(ComponentMixinsOuter) (created by TargetClassWithCtors)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by TargetClassWithCtors)
    in TargetClassWithCtors (created by ComponentMixinsInner)
    in ComponentMixinsInner (created by NamespacesConsumerComponent)
    in NamespacesConsumerComponent (created by WithMergedOptions)
    in WithMergedOptions (created by Context.Consumer)
    in WithMergedOptions(NamespacesConsumerComponent) (created by LoadNamespace)
    in LoadNamespace (created by WithMergedOptions)
    in WithMergedOptions (created by Context.Consumer)
    in LoadNamespace(ComponentMixinsInner) (created by ComponentMixinsOuter)
    in ComponentMixinsOuter (created by TargetClassWithCtors)
    in TargetClassWithCtors (created by ComponentMixinsInner)
    in ComponentMixinsInner (created by NamespacesConsumerComponent)
    in NamespacesConsumerComponent (created by WithMergedOptions)
    in WithMergedOptions (created by Context.Consumer)
    in WithMergedOptions(NamespacesConsumerComponent) (created by LoadNamespace)
    in LoadNamespace (created by WithMergedOptions)
    in WithMergedOptions (created by Context.Consumer)
    in LoadNamespace(ComponentMixinsInner) (created by ComponentMixinsOuter)
    in ComponentMixinsOuter
    in I18nextProvider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

The mailtrain Image version is: `4555d74e6f2d`

Is someone able to help me out here as I don't understand the problem fully or how to solve this.

Have a nice weekend together,

Bastian
