### ISSUE TITLE
[v2] Country statistics, is the country information linked to the subscriber timezone ?

### ISSUE THREAD

**Issue by ZephOne** [Mailtrain-org/mailtrain#649]
is the country information linked to the subscriber timezone or is there another mechanism?

**Comment by bures** [comment]
Which statistics do you have in mind?

**Comment by ZephOne** [comment]
Those ones:
![country_stats](https://user-images.githubusercontent.com/25317904/62297431-1d70ac80-b469-11e9-96b0-0f25252267bf.png)

**Comment by bures** [comment]
This one is based on IP address of the first open.

**Comment by ZephOne** [comment]
Ok then it does not seem to work. All openers'country are unknown. Is there an option to activate?

**Comment by bures** [comment]
If your Mailtrain is behind proxy, you have to tell it that it runs behind proxy.

**Comment by ZephOne** [comment]
Do you mean with the option --withProxy?
I so, I also did it.

**Comment by bures** [comment]
Yes. withProxy. Can you send a couple of rows from campaign_messages table?

**Comment by ZephOne** [comment]
I try but I got problem to access my mariadb container. I win this fight and send you that

**Comment by ZephOne** [comment]
Pfiou! it seems that MySQL user password max length is lesser than 100 char :smile: 
So here is what I have:
```mysql
+----+----------+------+--------------+--------------------+--------+------------------------------------+-------------+---------------------+---------------------+
| id | campaign | list | subscription | send_configuration | status | response                           | response_id | updated             | created             |
+----+----------+------+--------------+--------------------+--------+------------------------------------+-------------+---------------------+---------------------+
|  1 |        1 |    1 |            1 |                  1 |      1 | 250 2.0.0 Ok: queued as F25A7DB54E | F25A7DB54E  | 2019-08-02 16:11:05 | 2019-08-02 16:11:05 |
|  2 |        1 |    1 |            2 |                  1 |      1 | 250 2.0.0 Ok: queued as 3C6D7DB551 | 3C6D7DB551  | 2019-08-02 16:11:05 | 2019-08-02 16:11:05 |
|  3 |        1 |    1 |            3 |                  1 |      1 | 250 2.0.0 Ok: queued as 70AB7DB54E | 70AB7DB54E  | 2019-08-02 16:11:05 | 2019-08-02 16:11:05 |
+----+----------+------+--------------+--------------------+--------+------------------------------------+-------------+---------------------+---------------------+

```

**Comment by bures** [comment]
Sorry. I meant campaign_links.

**Comment by ZephOne** [comment]
Allr right, I have the ip, but all are the same:
```mysql
+----------+------+--------------+------+------------+-------------+---------+-------+---------------------+
| campaign | list | subscription | link | ip         | device_type | country | count | created             |
+----------+------+--------------+------+------------+-------------+---------+-------+---------------------+
|        1 |    1 |            1 |   -1 | 172.22.0.1 | desktop     | NULL    |     3 | 2019-08-02 16:11:22 |
|        1 |    1 |            1 |    0 | 172.22.0.1 | desktop     | NULL    |     1 | 2019-08-02 16:11:35 |
|        1 |    1 |            1 |    1 | 172.22.0.1 | desktop     | NULL    |     1 | 2019-08-02 16:11:35 |
|        1 |    1 |            1 |    2 | 172.22.0.1 | desktop     | NULL    |     1 | 2019-08-02 16:11:48 |
|        1 |    1 |            2 |   -1 | 172.22.0.1 | desktop     | NULL    |     2 | 2019-08-02 16:13:51 |
|        1 |    1 |            2 |    0 | 172.22.0.1 | desktop     | NULL    |     1 | 2019-08-02 16:13:55 |
|        1 |    1 |            2 |    3 | 172.22.0.1 | desktop     | NULL    |     1 | 2019-08-02 16:13:55 |
|        1 |    1 |            3 |   -1 | 172.22.0.1 | desktop     | NULL    |     2 | 2019-08-02 16:13:34 |
|        1 |    1 |            3 |    0 | 172.22.0.1 | desktop     | NULL    |     1 | 2019-08-02 16:13:38 |
|        1 |    1 |            3 |    1 | 172.22.0.1 | desktop     | NULL    |     1 | 2019-08-02 16:13:38 |
+----------+------+--------------+------+------------+-------------+---------+-------+---------------------+
```

**Comment by bures** [comment]
What server is 172.22.0.1?

**Comment by ZephOne** [comment]
Well this is something I don't know, I mean this is not my virtual private server ip. But `ip a` shows me:
```
...
808: br-1759e36b3080: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:39:93:cb:50 brd ff:ff:ff:ff:ff:ff
    inet 172.22.0.1/16 brd 172.22.255.255 scope global br-1759e36b3080
       valid_lft forever preferred_lft forever
...
```

I will ask my hosting service the meaning of this interface device: br-1759e36b3080

**Comment by ZephOne** [comment]
I was wrong, this is the ip address of my docker bridge

**Comment by bures** [comment]
Can you send me content of this file `server/config/production.yaml` after you start the container? In particular, I would like to see the `proxy` settings. 

Also, can you add the following line to server/routes/links.js:33
```
console.log(req.headers);
```
Try to open the campaign and send me the output of the `console.log`.

**Comment by ZephOne** [comment]
production.yaml:

```yml
www:
  host: 0.0.0.0
  proxy: true
  secret: "secret"
  trustedUrlBase: https://mailtrain.mydomain
  sandboxUrlBase: https://sbox.mailtrain.mydomain
  publicUrlBase: https://lists.mydomain

mysql:
  host: mysql

redis:
  enabled: true
  host: redis

log:
  level: info

builtinZoneMTA:
  log:
    level: warn
  mongo: mongodb://mongo:27017/zone-mta
  redis: redis://redis:6379/2

queue:
  processes: 5
```

And the output of the console.log:

```js
{
  host: '127.0.0.1:3004',
  connection: 'close',
  'user-agent': 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'accept-language': 'en-GB,en;q=0.5',
  'accept-encoding': 'gzip, deflate, br',
  cookie:
   '__cfduid=d057b993b0901505e67009ae783b6ec391553006856; SESSID=5938200948838c7d7547f77202a8a87b; connect.sid=s%3AMvElsONCVi_E0J-QOaO3r5IFylqmlxFb.ZLXVYSLTCmuuDu7DVKycuhwynQXl7Fi%2Fa%2F3uj8JWRIE; _csrf=QF2YSUHx8ayhnW-5h4zeuIkW',
  'upgrade-insecure-requests': '1',
  pragma: 'no-cache',
  'cache-control': 'no-cache'
}
```

**Comment by ZephOne** [comment]
production.yaml:

```yml
www:
  host: 0.0.0.0
  proxy: true
  secret: "secret"
  trustedUrlBase: https://mailtrain.mydomain
  sandboxUrlBase: https://sbox.mailtrain.mydomain
  publicUrlBase: https://lists.mydomain

mysql:
  host: mysql

redis:
  enabled: true
  host: redis

log:
  level: info

builtinZoneMTA:
  log:
    level: warn
  mongo: mongodb://mongo:27017/zone-mta
  redis: redis://redis:6379/2

queue:
  processes: 5
```

And the output of the console.log:

```js
{
  host: '127.0.0.1:3004',
  connection: 'close',
  'user-agent': 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'accept-language': 'en-GB,en;q=0.5',
  'accept-encoding': 'gzip, deflate, br',
  cookie:
   '__cfduid=d057b993b0901505e67009ae783b6ec391553006856; SESSID=secret; connect.sid=secret; _csrf=secret',
  'upgrade-insecure-requests': '1',
  pragma: 'no-cache',
  'cache-control': 'no-cache'
}
```
