### ISSUE TITLE
V2 Latest Docker image: migration file "20190722110000_hash_email.js" failed

### ISSUE THREAD

**Issue by brentkearney** [Mailtrain-org/mailtrain#650]
I setup V2 with docker in June, and just pulled the lastest image. The mailtrain container fails with a migration error:

```
$ docker-compose pull
Pulling mailtrain (mailtrain/mailtrain:latest)...
latest: Pulling from mailtrain/mailtrain
...
89e082c2d6f4: Pull complete
Digest: sha256:c1be6feab2b45be76642e80988b47dc49b26753e456415303e3b4fbe72775c39
Status: Downloaded newer image for mailtrain/mailtrain:latest
...
$ docker-compose up
Recreating mailtrain
...
mailtrain | nc: getaddrinfo: Name does not resolve
mailtrain | nc: getaddrinfo: Name does not resolve
...
mailtrain | info sql Database check completed
mailtrain | migration file "20190722110000_hash_email.js" failed
mailtrain | migration failed with error: ALTER TABLE `campaign_messages` ADD `hash_email` char(88) CHARACTER SET ascii - ER_DUP_FIELDNAME: Duplicate column name 'hash_email'
mailtrain | ERR! Error: ER_DUP_FIELDNAME: Duplicate column name 'hash_email'
mailtrain | ERR!     at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
mailtrain | ERR!     at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
mailtrain | ERR!     at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
mailtrain | ERR!     at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
mailtrain | ERR!     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
mailtrain | ERR!     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
mailtrain | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
mailtrain | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
mailtrain | ERR!     at Socket.emit (events.js:182:13)
mailtrain | ERR!     at Socket.EventEmitter.emit (domain.js:441:20)
mailtrain | ERR!     at addChunk (_stream_readable.js:283:12)
mailtrain | ERR!     at readableAddChunk (_stream_readable.js:264:11)
mailtrain | ERR!     at Socket.Readable.push (_stream_readable.js:219:10)
mailtrain | ERR!     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
mailtrain | ERR!     --------------------
mailtrain | ERR!     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
mailtrain | ERR!     at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)
mailtrain | ERR!     at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
mailtrain | ERR!     at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:313:9)
mailtrain | ERR!     at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:488:18)
mailtrain | ERR!     at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:79:10)
mailtrain | ERR!     at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
mailtrain | ERR!     at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)
mailtrain | ERR!     at /app/server/node_modules/knex/lib/transaction.js:232:21
mailtrain | ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain | ERR!     at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
mailtrain | ERR!     at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)
mailtrain | ERR!     at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)
mailtrain | ERR!     at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain | ERR!     at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)
mailtrain | ERR!     at Runner.queryArray (/app/server/node_modules/knex/lib/runner.js:207:40)
mailtrain | ERR!     at /app/server/node_modules/knex/lib/runner.js:44:23
mailtrain | ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain | ERR!     at /app/server/node_modules/bluebird/js/release/using.js:185:26
mailtrain | ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain | ERR!     at Promise._settlePromiseFromHandler (/app/server/node_modules/bluebird/js/release/promise.js:517:31)
mailtrain | ERR!     at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:574:18)
...

```

**Comment by brentkearney** [comment]
If I nuke the MySQL database, it starts up. But it would be nice to keep the data between versions...

Is there a way to override the default MySQL username & password (mailtrain/mailtrain) used by the mailtrain docker image?

**Comment by bures** [comment]
Could you send me the schema of the DB and contents of tables knex*? This seems like if you were trying to ingest DB dump that you got after some failed  migration. If this was the original dump from v1, the hash_email should not be there.

**Comment by ZephOne** [comment]
@brentkearney Yep you can override the default MySQL username/password.
In docker-compose.yml Change the value of MYSQL_USER and MYSQL_PASSWORD. Yet I think it's better to use environment variable for this kind of configuration using a .env file.
And also. override server/config/default.yaml by binding your own version of this file where you set the same MySQL setup.
```yaml
services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=<mysql_root_password>
    - MYSQL_DATABASE=<mysql_database>
    - MYSQL_USER=<mysql_username>
    - MYSQL_PASSWORD=<mysql_password>
    volumes:
    - mysql-data:/var/lib/mysql
# ...
  mailtrain:
    image: mailtrain/mailtrain:latest
    command: "The good command"
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - mailtrain-files:/app/server/files
    - /root/mailtrain/production.yaml:/app/server/config/default.yaml # You bind your own config
```

And in your config.yaml:

```yaml
# ...
mysql:
  host: <your host>
  user: <mysql_username>
  password: <mysql_password>
  database: <mysql_database>
  port: <your port>
  charset: <your charset, you can leave the one by default: utf8mb4>
  timezone: <your timezone>
# ...
```
