### ISSUE TITLE
V2: List import sending TIMESTAMP to DATETIME column

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#748]
It seems we are unable to import date columns into our lists. I checked the mysql schema for Date types and it is using `DATETIME`, but the import is sending dates formatted like `1970-01-01T00:00:00.000Z` a timestamp.

I'm happy to work on a PR for this if you can point me to the relevant files.

**Comment by ericuldall** [comment]
Error from import log:

```
ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '1970-01-01T00:00:00.000Z' for column 'custom_dob_2ppihxu7f' at row 1
```

**Comment by gerhardsletten** [comment]
Have the same problem, when I inspect the data-flow I see that field-value passed to [parsePostValue-func here](https://github.com/Mailtrain-org/mailtrain/blob/development/server/models/fields.js#L246) contains a setting-field that is a stringified object:

```
RowDataPacket {
  id: 3,
  name: 'Last Order Date',
  type: 'date',
  help: null,
  key: 'MERGE_LAST_ORDER_DATE',
  column: 'custom_last_order_date_3hzxci7lv',
  settings: '{"dateFormat":"eur"}', <-- here
  group: null,
  default_value: null,
  order_list: 3,
  order_subscribe: 3,
  order_manage: 3
}
```
And this will give `parseDate` and undefined first param:

```
parseDate(field.settings.dateFormat, value)
```
Have not looked into how data is stored in the database, but should this `settings` property be a string or should it be parsed to an object? 

The other issue with custom date-fields is that when converting a js Date object to a string and this data is posted to the ajax-route, the date-time is not a valid mysql-date. [Read more here](https://stackoverflow.com/questions/44304777/er-truncated-wrong-value-incorrect-datetime-value)

But a quick-fix for this to change the sql_mode in the docker-file: (not sure if this safe though..)

```
version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - mysql-data:/var/lib/mysql
    command: mysqld --sql_mode="" <-- Add this
```
