### ISSUE TITLE
Changing docker-entrypoint

### ISSUE THREAD

**Issue by heroic** [Mailtrain-org/mailtrain#753]
The current entrypoint script uses a lot of options to be passed via the docker command. This works with docker compose well, but with Kubernetes it's easier and more manageable to use ENV vars with values coming in from secrets.

I know it's also possible to pass ENV variable as values for the options, but it adds an unnecessary duplication. Can we look at modifying the file to use ENV vars instead of options? Here's an example of how we're using it today.

While we are at this, maybe we can add a helm chart for deploying mailtrain on Kubernetes as well. I can share the charts we are using, to help.

PS: We've left out the variable we are not using, so this file is for representation only.

```
#!/bin/bash
set -e

cat > server/config/production.yaml <<EOT
www:
  host: 0.0.0.0
  proxy: true
  secret: "`pwgen -1`"
  trustedUrlBase: $TRUSTED_URL
  sandboxUrlBase: $SANDBOX_URL
  publicUrlBase: $PUBLIC_URL
mysql:
  host: $MYSQL_HOSTNAME
  user: $MYSQL_USERNAME
  password: $MYSQL_PASSWORD
  database: $MYSQL_DATABASE
redis:
  enabled: true
  host: $REDIS_HOST
gdpr:
  deleteDataAfterUnsubscribe:
    enabled: false
  deleteSubscriptionAfterUnsubscribe:
    enabled: false
builtinZoneMTA:
  enabled: false
log:
  level: info
queue:
  processes: 5
ldap:
  enabled: $withLdap
  host: $ldapHost
  port: $ldapPort
  secure: $ldapSecure
  $ldapBindUserLine
  $ldapBindPassLine
  $ldapFilterLine
  $ldapBaseDNLine
  $ldapUidTagLine
EOT

cat > server/services/workers/reports/config/production.yaml <<EOT
mysql:
  host: $MYSQL_HOSTNAME
  user: $MYSQL_USERNAME
  password: $MYSQL_PASSWORD
  database: $MYSQL_DATABASE
log:
  level: warn
EOT

cd server
NODE_ENV=production node index.js
```
