### ISSUE TITLE
V2: Ubuntu 18.04 Install Issues

### ISSUE THREAD

**Issue by talheim-it** [Mailtrain-org/mailtrain#766]
Hello,

I am running into a few issues:
**1. Install modules (npm-sass)**
Errors by running the script as root because of permissions, npm should be run as mailtrain in that case.

It should be fixed by:
`npm install --unsafe-perm -g node-sass`

2. After failing will the prod install for Ubuntu 18.04, I tried to just run local install.
```
When I start mailtrain to open the webui via 127.0.0.1:3000, just a blank page:
GET http://127.0.0.1:3000/client/mailtrain.css net::ERR_ABORTED 404 (Not Found)
(index):35 GET http://127.0.0.1:3000/client/root.js net::ERR_ABORTED 404 (Not Found)
(index):42 Uncaught ReferenceError: MailtrainReactBody is not defined
    at HTMLDocument.<anonymous> ((index):42)
(anonymous) @ (index):42
DevTools failed to parse SourceMap: http://127.0.0.1:3000/static-npm/bootstrap.min.js.map
DevTools failed to parse SourceMap: http://127.0.0.1:3000/static-npm/popper.min.js.map
DevTools failed to parse SourceMap: http://127.0.0.1:3000/static-npm/coreui.min.js.map
```
production.yml:
```
www:
  host: 0.0.0.0
  proxy: false
  secret: "too8caeG"
  trustedUrlBase: http://127.0.0.1:3000
  sandboxUrlBase: http://127.0.0.1:3003
  publicUrlBase: http://127.0.0.1:3004
```
the other both showing me 
`Cannot GET /`

I have no clue why this is coming. Anyone has an idea?

Thanks!

**Comment by bures** [comment]
My guess is that since the installer aborted, the client has not been compiled. You have to go to "client" directory and run `npm run build`.

**Comment by talheim-it** [comment]
@bures thanks, that was the trick. The install Script didn't show me that it has troubles for the client. But maybe it was not completely build because of the point 1.

So it is running by now. Next step is I want to run it behind an nginx config (also tried with apache2, same situation).
I am receiving mixed content warnings which make no sense because the same config is working on an openproject server:

```
location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:3000;
        proxy_redirect off;
 }
```
Errors I got from the dev-tools:

```
Mixed Content: The page at 'https://127.0.0.1/' was loaded over HTTPS, but requested an insecure stylesheet 'http://127.0.0.1:3000/client/mailtrain.css'. This request has been blocked; the content must be served over HTTPS.
5Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure script '<URL>'. This request has been blocked; the content must be served over HTTPS.
(index):26 Warning: Misconfigured urlBases. If the website does not work, check the settings of www.trustedUrlBase, www.sandboxUrlBase and www.publicUrlBase in server config file.
(anonymous) @ (index):26
(index):42 Uncaught ReferenceError: MailtrainReactBody is not defined
    at HTMLDocument.<anonymous> ((index):42)
(anonymous) @ (index):42
2(index):1 Mixed Content: The page at 'https://127.0.0.1/' was loaded over HTTPS, but requested an insecure favicon 'http://127.0.0.1:3000/static/favicon.ico'. This request has been blocked; the content must be served over HTTPS.
```

The NGINX config worked with mailtrain v1 without troubles.

**Comment by talheim-it** [comment]
@bures so usually the config I have is working with nodejs Applications, something is different and just has to do with the new urls type:
www.trustedUrlBase, www.sandboxUrlBase and www.publicUrlBase

That was not part in the v1, so what does it do exactly? And what do they need to work with the proxy correctly? I tried to setup in prod environment:
https://newsletter.talheim-records.com/

Konfig for nginx:
```
upstream mailtrain {
  server newsletter.talheim-records.com:3000 fail_timeout=0;
}

server {
    if ($host = newsletter.talheim-records.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name newsletter.talheim-records.com;
    return         301 https://$server_name$request_uri;
}

server {
    listen 443 http2 ssl;
    listen [::]:443 http2 ssl;
    server_name newsletter.talheim-records.com;
    access_log /var/log/nginx/newslettertool.talheim-records.com.log;

    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/newsletter.talheim-records.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/newsletter.talheim-records.com/privkey.pem;
    include /etc/nginx/conf.d/ssl.conf;

    client_max_body_size 30m;

    location ~ /.well-known {
                allow all;
    }

    location / {
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   	proxy_set_header X-Forwarded-Host newsletter.talheim-records.com;
   	proxy_set_header X-Forwarded-Proto https;
	proxy_set_header X-NginX-Proxy true;
   	proxy_redirect off;
   	proxy_pass http://mailtrain;
    }
}

```

Mailtrain production.yaml:
```
user: mailtrain
group: mailtrain
roUser: nobody
roGroup: nobody

www:
  host: 0.0.0.0
  proxy: true
  secret: "too8caeG"
  trustedUrlBase: http://newsletter.talheim-records.com:3000
  sandboxUrlBase: http://127.0.0.1:3003
  publicUrlBase: http://127.0.0.1:3004
  postsize: 2M

mysql:
  password: "

redis:
  enabled: true

log:
  level: info

builtinZoneMTA:
  log:
    level: warn

queue:
  processes: 5

seleniumWebDriver:
  browser: phantomjs

```

Where is the issue?

Direct access over http: with port 3000 is working.

**Comment by talheim-it** [comment]
I also found:
https://gitlab.d3s.mff.cuni.cz/evif/ivis-core/tree/master/server

Since this is the base I tried the options:
```
user: mailtrain
group: mailtrain
roUser: nobody
roGroup: nobody

www:
  host: 0.0.0.0
  proxy: false
  secret: "too8caeG"
  trustedPort: 443
  trustedPortIsHttps: true
  trustedUrlBase: https://newsletter.talheim-records.com:443
  sandboxUrlBase: https://127.0.0.1:3003
  publicPort: 8443
  publicPortIsHttps: true
  publicUrlBase: https://newsletter.talheim-records.com:8443
  postsize: 2M

certs:
www:
    serverCert: /etc/letsencrypt/live/newsletter.talheim-records.com/cert.pem
    serverKey: /etc/letsencrypt/live/newsletter.talheim-records.com/privkey.pem

mysql:
  password: "eYaizaew8sue"

redis:
  enabled: true

log:
  level: info

builtinZoneMTA:
  log:
    level: warn

queue:
  processes: 5

seleniumWebDriver:
  browser: phantomjs
```
The additonal www and cert options also not working. I am getting an SSL error.
