### ISSUE TITLE
V2: why all those services?

### ISSUE THREAD

**Issue by tcurdt** [Mailtrain-org/mailtrain#828]
I wanted to give V2 a try but looking at the [docker compose file](https://raw.githubusercontent.com/Mailtrain-org/mailtrain/development/docker-compose.yml) I am a bit confused.

- mariadb
- redis
- mongo

Why all those services? Especially mongo **and** mariadb?

**Comment by tcurdt** [comment]
Is there a better place to ask this question?

**Comment by bures** [comment]
MariaDB - data persistence for Mailtrain

Redis - session store for Mailtrain (primarily authentication cookies)

Mongo - data persistence for built-in ZoneMTA. If you don't use the built-in ZoneMTA, you can leave Mongo out

**Comment by tcurdt** [comment]
Ah, perfect! Thanks!

**Comment by tcurdt** [comment]
When I just remove mongo from the docker compose I am getting

```
mailtrain_1  | Info: Waiting for MongoDB Server
mailtrain_1  | nc: getaddrinfo: Name does not resolve
mailtrain_1  | nc: getaddrinfo: Name does not resolve
mailtrain_1  | nc: getaddrinfo: Name does not resolve
```

What do I need to do to disable this, @bures?

**Comment by bures** [comment]
Edit the docker-entrypoint.sh in the container.

**Comment by tcurdt** [comment]
Urgh. Would be nice to have an env variable for that.

**Comment by programster** [comment]
I too was a bit surprised by all the services, but saw that I could turn off redis (boolean env), and I could turn off zonemta, which I deduced might allow me to turn off Mongo (which it seems you confirmed in this thread). So if I want a super lean deployment in terms of memory, should the following docker-compose be valid/work? It seems to spin up okay, but haven't tested everything yet.

```yaml
---
version: "3.8"
services:
  mailtrain:
    image: mailtrain/mailtrain:v2.20210609.0
    ports:
    - 3000:3000
    - 3003:3003
    - 3004:3004
    restart: unless-stopped
    container_name: mailtrain
    volumes:
    - type: volume
      target: /app/server/files
      source: mailtrain-files
    environment:
    - PORT_TRUSTED=3000
    - PORT_SANDBOX=3003
    - PORT_PUBLIC=3004
    - URL_BASE_TRUSTED=http://localhost:3000
    - URL_BASE_SANDBOX=http://localhost:3003
    - URL_BASE_PUBLIC=http://localhost:3004
    - WWW_PROXY=0
    - WITH_REDIS=0
    - WWW_SECRET=xxxxxxxxxx
    - WITH_ZONE_MTA=0
    - MYSQL_HOST=db
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=xxxxxxxxxx
    depends_on:
    - db
  db:
    image: mariadb:10.6
    restart: unless-stopped
    container_name: db
    volumes:
    - type: volume
      target: /var/lib/mysql
      source: db-data
    environment:
    - MARIADB_RANDOM_ROOT_PASSWORD=1
    - MARIADB_DATABASE=mailtrain
    - MARIADB_USER=mailtrain
    - MARIADB_PASSWORD=xxxxxxxxxx
volumes:
  mailtrain-files:
    driver: local
  db-data:
    driver: local
...
```
