### ISSUE TITLE
V2 LDAP not working

### ISSUE THREAD

**Issue by maxemann96** [Mailtrain-org/mailtrain#862]
Hello,
I setup the server with ldap enabled, but the following messages are printed to log:
```
info LDAP Module "passport-ldapjs" not installed. It will not be used for LDAP auth.
info LDAP Module "passport-ldapauth" not installed. It will not be used for LDAP auth.
```

As indicated, mailtrain never tries to connect to my ldap server.
Im using the latest docker image with the following ldap config (excerpt from mounted /app/server/config/production.yaml):

```
ldap:
  enabled: true
  host: openldap
  port: 389
  secure: true
  baseDN: {{ BASE_DN }}
  filter: (&(&(objectclass=inetOrgPerson)(memberof=cn=mailtrain,ou=apps,{{ BASE_DN }}))(|(cn={{username}})(|(mailPrimaryAddress={{username}})(mail={{username}}))(|(cn={{username}}))))
  uidTag: entryUUID
  nameTag: displayName
  bindUser: cn=mailtrain,ou=apps,{{ BASE_DN }}
  bindPassword: {{ PASSWORD }}
```

With basedn and password substituted with the correct values. Am I missing something?
