### ISSUE TITLE
Redis connection issues

### ISSUE THREAD

**Issue by whysthatso** [Mailtrain-org/mailtrain#876]
I'm running this setup via docker-composer:

```
version: '3'

services:
  mailtrain:
    image: mailtrain/mailtrain:latest
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - mailtrain-files:/app/server/files
    extra_hosts:
    - db.domain.net:10.0.0.154
    environment:
    - PORT_TRUSTED=3000
    - PORT_SANDBOX=3003
    - PORT_PUBLIC=3004
    - URL_BASE_TRUSTED=https://trusted.mailtrain.domain.net
    - URL_BASE_SANDBOX=https://sandbox.mailtrain.domain.net
    - URL_BASE_PUBLIC=https://public.mailtrain.domain.net
    - WWW_HOST=0.0.0.0
    - WWW_PROXY=true
    - WWW_SECRET=pass
    - MONGO_HOST=db.domain.net
    - WITH_REDIS=false
    - REDIS_HOST=db.domain.net
    - MYSQL_HOST=db.domain.net
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=pass

volumes:
  mailtrain-files:
```

I have an external redis, mongo mysql instance all of which are confirmed accessible from inside the running mailtrain container.

everything starts fine and is apparently working well.

while running i get this error in the logs:

```
Apr 07 15:22:07 bbox004 docker-compose[15596]: mailtrain_1  | ERR! DNS DNSREDISERR SET key=lookup_db.domain.net_4_0_false error=Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
Apr 07 15:22:13 bbox004 docker-compose[15596]: mailtrain_1  | ERR! Redis/48 connect ETIMEDOUT
```
both messages repeat more or less alternating.

any clue what this is all about?
