### ISSUE TITLE
Traefik does not route to mailtrain url endpoint

### ISSUE THREAD

**Issue by luhgit** [Mailtrain-org/mailtrain#886]
Hi,

I am trying to setup `mailtrain` on my VPS behind `Traefik` proxy. I am using Traefik as a loadbalancer for all of my services. I have setup the appropriate labels for Mailtrain services (trusted, sandbox, public). Traefik generates the certificates in acme json for all three URL but when I try to reach I get the following error:

`404 page not found`

Contents of `docker-compose.yml`:
```
version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
    - redis-data:/data

  mongo:
    image: mongo:4-xenial
    volumes:
    - mongo-data:/data/db

  mailtrain:
    image: mailtrain/mailtrain:latest
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - mailtrain-files:/app/server/files

volumes:
  mysql-data:
  redis-data:
  mongo-data:
  mailtrain-files:
```

The contents of `docker-compose.override.yml`:
```
version: '3'

services:
    # Frontend
    mailtrain:
        depends_on:
            - mysql
            - redis
            - mongo
        labels:
            - "traefik.enable=true"

            # Mailtrain - Trusted (For end users to create marketing compaigns)
            - "traefik.http.routers.mailtrain-trusted.rule=Host(`mailtrain.example.com`)"
            - "traefik.http.middlewares.mailtrain-trusted-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.mailtrain-trusted.middlewares=mailtrain-trusted-https-redirect"
            - "traefik.http.routers.mailtrain-trusted.entrypoints=https"
            - "traefik.http.routers.mailtrain-trusted.tls=true"
            - "traefik.http.routers.mailtrain-trusted.tls.certresolver=http"
            - "traefik.http.routers.mailtrain-trusted.service=mailtrain-trusted"
            - "traefik.http.services.mailtrain-trusted.loadbalancer.server.port=3000"

            # Mailtrain - Sandbox (Used to host WYSIWYG template editors - not directly visible to user)
            - "traefik.http.routers.mailtrain-sandbox.rule=Host(`sbox.mailtrain.example.com`)"
            - "traefik.http.middlewares.mailtrain-sandbox-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.mailtrain-sandbox.middlewares=mailtrain-sandbox-https-redirect"
            - "traefik.http.routers.mailtrain-sandbox.entrypoints=https"
            - "traefik.http.routers.mailtrain-sandbox.tls=true"
            - "traefik.http.routers.mailtrain-sandbox.tls.certresolver=http"
            - "traefik.http.routers.mailtrain-sandbox.service=mailtrain-sandbox"
            - "traefik.http.services.mailtrain-sandbox.loadbalancer.server.port=3003"

            # Mailtrain - Public (Endpoint for subscribers)
            - "traefik.http.routers.mailtrain-public.rule=Host(`lists.example.com`)"
            - "traefik.http.middlewares.mailtrain-public-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.mailtrain-public.middlewares=mailtrain-public-https-redirect"
            - "traefik.http.routers.mailtrain-public.entrypoints=https"
            - "traefik.http.routers.mailtrain-public.tls=true"
            - "traefik.http.routers.mailtrain-public.tls.certresolver=http"
            - "traefik.http.routers.mailtrain-public.service=mailtrain-public"
            - "traefik.http.services.mailtrain-public.loadbalancer.server.port=3004"

            - "traefik.docker.network=proxy"
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - WITH_PROXY=true
            - URL_BASE_TRUSTED='https://mailtrain.example.com'
            - URL_BASE_SANDBOX='https://sbox.mailtrain.example.com'
            - URL_BASE_PUBLIC='https://lists.example.com'
            - PORT_TRUSTED=3000
            - PORT_SANDBOX=3003
            - PORT_PUBLIC=3004
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=mailtrain
            - MYSQL_USER=mailtrain
            - MYSQL_PASSWORD=mailtrain
        networks:
            - proxy
    
    mysql:
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
    redis:
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro   
    mongo:
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - mongo-data-config:/data/configdb
networks:
    proxy:
        external: true

volumes:
    mongo-data-config:
```

What am I doing wrong? Any help will be much appreciated. Thanks.

**Comment by hunterlong** [comment]
I'm getting same issue.

**Comment by maxemann96** [comment]
What url (i.e. which subdomain) do you exactly try to reach? In my configuration sbox and lists yielding to a 404, but not mailtrain.example.com. The sbox iframe and the unsubscription links are working properly

**Comment by luhgit** [comment]
I added the solution here: [Link to solution](https://stackoverflow.com/questions/61303360/mailcow-setup-behind-traefik-proxy-causes-https-certificate-error/61495429#61495429)

**Comment by hunterlong** [comment]
@luhgit anyway you can post your docker-compose.yml?

**Comment by wschopohl** [comment]
This docker-compose.yml is working for me.
```
version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
    - internal

  redis:
    image: redis:5
    volumes:
    - redis-data:/data
    networks:
    - internal

  mongo:
    image: mongo:4-xenial
    volumes:
    - mongo-data:/data/db
    networks:
    - internal

  mailtrain:
    image: mailtrain/mailtrain:latest
    volumes:
    - mailtrain-files:/app/server/files
    labels:
    - traefik.enable=true
    - traefik.docker.network=web
    - traefik.trusted.port=3000
    - traefik.trusted.frontend.rule=Host:mailtrain.domain.com
    - traefik.sandbox.port=3003
    - traefik.sandbox.frontend.rule=Host:sbox.mailtrain.domain.com
    - traefik.public.port=3004
    - traefik.public.frontend.rule=Host:lists.domain.com
    environment:
    - WWW_PROXY=true
    - URL_BASE_TRUSTED=https://mailtrain.domain.com
    - URL_BASE_SANDBOX=https://sbox.domain.com
    - URL_BASE_PUBLIC=https://lists.domain.com
    networks:
    - web
    - internal

volumes:
  mysql-data:
  redis-data:
  mongo-data:
  mailtrain-files:

networks:
  web:
    external: true
  internal:
```
