### ISSUE TITLE
ERROR when deploying mailtrain with caddy reverse proxy

### ISSUE THREAD

**Issue by mingsterism** [Mailtrain-org/mailtrain#893]
I'm getting an openssl issue when deploying mailtrain with a caddy reverse proxy sitting in front of the docker containers. 
This is my docker-compose.override.yml file

```
version: '3'
services:
  proxy: 
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
  mailtrain:
    environment:
    - WWW_PROXY
    - URL_BASE_TRUSTED
    - URL_BASE_SANDBOX
    - URL_BASE_PUBLIC
```

When i try to send a test mailtrain email, it get these errors in the proxy server
```
tls: client offered only unsupported versions: [302 301]
```

Is mailtrain using an old version of openssl? 
Thanks
